# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False)),
                ('name_brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id_departure', models.AutoField(primary_key=True, serialize=False)),
                ('id_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_product', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField(blank=True, null=True)),
                ('id_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Tools', 'Tools'), ('Foods', 'Foods'), ('Clothes', 'Clothes'), ('Shoes', 'Shoes'), ('Accesories', 'Accesories'), ('Otro', 'Otro')], max_length=50)),
                ('serial', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('nit_provider', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name_provider', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField()),
                ('cell_phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Tools', 'Tools'), ('Foods', 'Foods'), ('Clothes', 'Clothes'), ('Shoes', 'Shoes'), ('Accesories', 'Accesories'), ('Otro', 'Otro')], max_length=50)),
                ('level', models.CharField(choices=[('Local', 'Local'), ('Local', 'National'), ('International', 'International'), ('Otro', 'Otro')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id_purchase', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('date_buy', models.DateField()),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('cost', models.IntegerField()),
                ('value_sale', models.IntegerField()),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Brand')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Product')),
                ('nit_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Provider')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Product'),
        ),
        migrations.AddField(
            model_name='departure',
            name='id_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='inventario.Purchase'),
        ),
    ]
