# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='id_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Purchase'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='level',
            field=models.CharField(choices=[('Local', 'Local'), ('National', 'National'), ('International', 'International'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
