# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20180817_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='date_dep',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departure',
            name='id_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Purchase'),
        ),
    ]
