# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20180822_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='date_dep',
            field=models.DateField(blank=True, null=True),
        ),
    ]
