# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20180822_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
